import { SubsidiaryCompany, Location } from './types';

// Static mock data for subsidiaries
export const SUBSIDIARIES: SubsidiaryCompany[] = [
  {
    id: 'sub-001',
    officialName: 'Meridian Energy Solutions GmbH',
    country: 'Germany',
    city: 'Munich',
    postalCode: '80331',
    address: 'Maximilianstrasse 42, Munich',
    naceCode: 'D35',
    naceDescription: 'Electricity, gas, steam and air conditioning supply',
    capacityReport: {
      fileName: 'meridian_capacity_2024.pdf',
      fileSize: 2450000,
      uploadedAt: '2024-01-15',
      uploadedBy: 'Hans Mueller',
    },
    authorizedRepresentative: 'Hans Mueller',
    representativeContact: 'h.mueller@meridian-energy.de',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-001-1',
        name: 'Munich Headquarters',
        address: 'Maximilianstrasse 42, 80331 Munich',
        activityDescription: 'Corporate headquarters and administrative functions',
        generalInfo: 'Main office building with 450 employees',
        authorizedPerson: 'Hans Mueller',
        email: 'h.mueller@meridian-energy.de',
        department: 'Administration',
        createdAt: '2023-01-10',
        updatedAt: '2024-02-15',
      },
      {
        id: 'loc-001-2',
        name: 'Frankfurt Operations Center',
        address: 'Industriepark 15, 60329 Frankfurt',
        activityDescription: 'Energy distribution and grid management operations',
        generalInfo: 'Operations center managing regional grid infrastructure',
        authorizedPerson: 'Klaus Schmidt',
        email: 'k.schmidt@meridian-energy.de',
        department: 'Operations',
        createdAt: '2023-03-20',
        updatedAt: '2024-01-28',
      },
      {
        id: 'loc-001-3',
        name: 'Hamburg Service Hub',
        address: 'Hafenstrasse 88, 20457 Hamburg',
        activityDescription: 'Customer service and technical support center',
        generalInfo: 'Northern region service center with 120 technicians',
        authorizedPerson: 'Maria Weber',
        email: 'm.weber@meridian-energy.de',
        department: 'Engineering',
        createdAt: '2023-06-05',
        updatedAt: '2024-03-01',
      },
    ],
    hasChildSubsidiaries: true,
    childSubsidiaryCount: 2,
    status: 'active',
    createdAt: '2023-01-10',
    updatedAt: '2024-03-15',
  },
  {
    id: 'sub-002',
    officialName: 'Nordic Steel Industries AB',
    country: 'Sweden',
    city: 'Stockholm',
    postalCode: '111 57',
    address: 'Kungsgatan 18, Stockholm',
    naceCode: 'C24',
    naceDescription: 'Manufacture of basic metals',
    capacityReport: {
      fileName: 'nordic_steel_capacity_2024.pdf',
      fileSize: 3200000,
      uploadedAt: '2024-02-01',
      uploadedBy: 'Erik Lindqvist',
    },
    authorizedRepresentative: 'Erik Lindqvist',
    representativeContact: 'erik.lindqvist@nordicsteel.se',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-002-1',
        name: 'Stockholm HQ',
        address: 'Kungsgatan 18, 111 57 Stockholm',
        activityDescription: 'Corporate management and sales',
        generalInfo: 'Head office with executive and sales teams',
        authorizedPerson: 'Erik Lindqvist',
        email: 'erik.lindqvist@nordicsteel.se',
        department: 'Administration',
        createdAt: '2022-06-15',
        updatedAt: '2024-01-20',
      },
      {
        id: 'loc-002-2',
        name: 'Lulea Production Plant',
        address: 'Stalgatan 5, 971 28 Lulea',
        activityDescription: 'Primary steel production and processing',
        generalInfo: 'Main production facility with blast furnaces',
        authorizedPerson: 'Anna Johansson',
        email: 'anna.johansson@nordicsteel.se',
        department: 'Production',
        createdAt: '2022-06-15',
        updatedAt: '2024-02-28',
      },
    ],
    hasChildSubsidiaries: false,
    childSubsidiaryCount: 0,
    status: 'active',
    createdAt: '2022-06-15',
    updatedAt: '2024-02-28',
  },
  {
    id: 'sub-003',
    officialName: 'Atlantic Shipping Ltd',
    country: 'United Kingdom',
    city: 'London',
    postalCode: 'E14 5AB',
    address: '25 Canada Square, Canary Wharf, London',
    naceCode: 'H50',
    naceDescription: 'Water transport',
    capacityReport: null,
    authorizedRepresentative: 'James Thompson',
    representativeContact: 'j.thompson@atlanticshipping.co.uk',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-003-1',
        name: 'London HQ',
        address: '25 Canada Square, Canary Wharf, E14 5AB London',
        activityDescription: 'Corporate headquarters and fleet management',
        generalInfo: 'Main office handling global shipping operations',
        authorizedPerson: 'James Thompson',
        email: 'j.thompson@atlanticshipping.co.uk',
        department: 'Operations',
        createdAt: '2021-09-01',
        updatedAt: '2024-03-10',
      },
      {
        id: 'loc-003-2',
        name: 'Southampton Port Operations',
        address: 'Ocean Way, Southampton SO14 3QN',
        activityDescription: 'Port logistics and container handling',
        generalInfo: 'Major UK port operations hub',
        authorizedPerson: 'David Clarke',
        email: 'd.clarke@atlanticshipping.co.uk',
        department: 'Logistics',
        createdAt: '2021-09-01',
        updatedAt: '2024-02-15',
      },
      {
        id: 'loc-003-3',
        name: 'Liverpool Terminal',
        address: 'Regent Road, Liverpool L20 8DD',
        activityDescription: 'Container terminal operations',
        generalInfo: 'Northern England container terminal',
        authorizedPerson: 'Sarah Wilson',
        email: 's.wilson@atlanticshipping.co.uk',
        department: 'Logistics',
        createdAt: '2022-03-15',
        updatedAt: '2024-01-30',
      },
    ],
    hasChildSubsidiaries: true,
    childSubsidiaryCount: 1,
    status: 'active',
    createdAt: '2021-09-01',
    updatedAt: '2024-03-10',
  },
  {
    id: 'sub-004',
    officialName: 'Petrochem Iberia S.A.',
    country: 'Spain',
    city: 'Madrid',
    postalCode: '28046',
    address: 'Paseo de la Castellana 200, Madrid',
    naceCode: 'C19',
    naceDescription: 'Manufacture of coke and refined petroleum products',
    capacityReport: {
      fileName: 'petrochem_capacity_report.pdf',
      fileSize: 4100000,
      uploadedAt: '2023-12-10',
      uploadedBy: 'Carlos Garcia',
    },
    authorizedRepresentative: 'Carlos Garcia',
    representativeContact: 'c.garcia@petrochemiberia.es',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-004-1',
        name: 'Madrid Corporate Office',
        address: 'Paseo de la Castellana 200, 28046 Madrid',
        activityDescription: 'Corporate management and administration',
        generalInfo: 'Corporate headquarters',
        authorizedPerson: 'Carlos Garcia',
        email: 'c.garcia@petrochemiberia.es',
        department: 'Administration',
        createdAt: '2020-05-20',
        updatedAt: '2024-01-15',
      },
      {
        id: 'loc-004-2',
        name: 'Tarragona Refinery',
        address: 'Poligono Industrial, 43006 Tarragona',
        activityDescription: 'Oil refining and petrochemical production',
        generalInfo: 'Main refinery with 500,000 bbl/day capacity',
        authorizedPerson: 'Miguel Santos',
        email: 'm.santos@petrochemiberia.es',
        department: 'Production',
        createdAt: '2020-05-20',
        updatedAt: '2024-03-05',
      },
    ],
    hasChildSubsidiaries: false,
    childSubsidiaryCount: 0,
    status: 'active',
    createdAt: '2020-05-20',
    updatedAt: '2024-03-05',
  },
  {
    id: 'sub-005',
    officialName: 'TechnoLogistics BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    postalCode: '3011 AD',
    address: 'Coolsingel 104, Rotterdam',
    naceCode: 'H52',
    naceDescription: 'Warehousing and support activities for transportation',
    capacityReport: null,
    authorizedRepresentative: 'Willem van der Berg',
    representativeContact: 'w.vanderberg@technologistics.nl',
    hasMultipleLocations: false,
    locations: [
      {
        id: 'loc-005-1',
        name: 'Rotterdam Distribution Center',
        address: 'Coolsingel 104, 3011 AD Rotterdam',
        activityDescription: 'Warehouse and distribution operations',
        generalInfo: 'Central European distribution hub',
        authorizedPerson: 'Willem van der Berg',
        email: 'w.vanderberg@technologistics.nl',
        department: 'Logistics',
        createdAt: '2023-02-01',
        updatedAt: '2024-02-20',
      },
    ],
    hasChildSubsidiaries: false,
    childSubsidiaryCount: 0,
    status: 'active',
    createdAt: '2023-02-01',
    updatedAt: '2024-02-20',
  },
  {
    id: 'sub-006',
    officialName: 'Anadolu Celik A.S.',
    country: 'Turkey',
    city: 'Istanbul',
    postalCode: '34394',
    address: 'Levent Mahallesi, Buyukdere Cad. No:185, Sisli',
    naceCode: 'C24',
    naceDescription: 'Manufacture of basic metals',
    capacityReport: {
      fileName: 'anadolu_celik_kapasite_raporu.pdf',
      fileSize: 2800000,
      uploadedAt: '2024-01-20',
      uploadedBy: 'Mehmet Yilmaz',
    },
    authorizedRepresentative: 'Mehmet Yilmaz',
    representativeContact: 'm.yilmaz@anadolucelik.com.tr',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-006-1',
        name: 'Istanbul Genel Mudurluk',
        address: 'Levent Mahallesi, Buyukdere Cad. No:185, 34394 Sisli, Istanbul',
        activityDescription: 'Kurumsal yonetim ve idari islemler',
        generalInfo: 'Sirket merkezi ve yonetim ofisleri',
        authorizedPerson: 'Mehmet Yilmaz',
        email: 'm.yilmaz@anadolucelik.com.tr',
        department: 'Administration',
        createdAt: '2019-08-15',
        updatedAt: '2024-03-01',
      },
      {
        id: 'loc-006-2',
        name: 'Iskenderun Celik Fabrikasi',
        address: 'Organize Sanayi Bolgesi, 31200 Iskenderun, Hatay',
        activityDescription: 'Celik uretimi ve isleme',
        generalInfo: 'Ana uretim tesisi - yillik 2 milyon ton kapasite',
        authorizedPerson: 'Ali Demir',
        email: 'a.demir@anadolucelik.com.tr',
        department: 'Production',
        createdAt: '2019-08-15',
        updatedAt: '2024-02-28',
      },
      {
        id: 'loc-006-3',
        name: 'Izmir Lojistik Merkezi',
        address: 'Aliaga Liman Bolgesi, 35800 Izmir',
        activityDescription: 'Liman operasyonlari ve lojistik',
        generalInfo: 'Ihracat ve ithalat lojistik merkezi',
        authorizedPerson: 'Ayse Kaya',
        email: 'a.kaya@anadolucelik.com.tr',
        department: 'Logistics',
        createdAt: '2020-03-10',
        updatedAt: '2024-01-15',
      },
    ],
    hasChildSubsidiaries: true,
    childSubsidiaryCount: 1,
    status: 'active',
    createdAt: '2019-08-15',
    updatedAt: '2024-03-01',
  },
  {
    id: 'sub-007',
    officialName: 'Alpine Chemical AG',
    country: 'Switzerland',
    city: 'Basel',
    postalCode: '4051',
    address: 'Steinenvorstadt 55, Basel',
    naceCode: 'C20',
    naceDescription: 'Manufacture of chemicals and chemical products',
    capacityReport: {
      fileName: 'alpine_chemical_capacity.pdf',
      fileSize: 1900000,
      uploadedAt: '2023-11-30',
      uploadedBy: 'Thomas Brunner',
    },
    authorizedRepresentative: 'Thomas Brunner',
    representativeContact: 't.brunner@alpinechemical.ch',
    hasMultipleLocations: false,
    locations: [
      {
        id: 'loc-007-1',
        name: 'Basel Production Facility',
        address: 'Steinenvorstadt 55, 4051 Basel',
        activityDescription: 'Specialty chemical manufacturing',
        generalInfo: 'R&D center and production facility',
        authorizedPerson: 'Thomas Brunner',
        email: 't.brunner@alpinechemical.ch',
        department: 'Research & Development',
        createdAt: '2021-04-01',
        updatedAt: '2024-02-10',
      },
    ],
    hasChildSubsidiaries: false,
    childSubsidiaryCount: 0,
    status: 'active',
    createdAt: '2021-04-01',
    updatedAt: '2024-02-10',
  },
  {
    id: 'sub-008',
    officialName: 'Green Transport Italia S.r.l.',
    country: 'Italy',
    city: 'Milan',
    postalCode: '20121',
    address: 'Via Monte Napoleone 8, Milan',
    naceCode: 'H49',
    naceDescription: 'Land transport and transport via pipelines',
    capacityReport: null,
    authorizedRepresentative: 'Marco Rossi',
    representativeContact: 'm.rossi@greentransport.it',
    hasMultipleLocations: true,
    locations: [
      {
        id: 'loc-008-1',
        name: 'Milan Office',
        address: 'Via Monte Napoleone 8, 20121 Milan',
        activityDescription: 'Corporate office and fleet management',
        generalInfo: 'Northern Italy operations headquarters',
        authorizedPerson: 'Marco Rossi',
        email: 'm.rossi@greentransport.it',
        department: 'Operations',
        createdAt: '2022-09-01',
        updatedAt: '2024-01-25',
      },
      {
        id: 'loc-008-2',
        name: 'Rome Depot',
        address: 'Via Tiburtina 1250, 00156 Rome',
        activityDescription: 'Vehicle depot and maintenance center',
        generalInfo: 'Central Italy fleet base',
        authorizedPerson: 'Giulia Bianchi',
        email: 'g.bianchi@greentransport.it',
        department: 'Maintenance',
        createdAt: '2022-11-15',
        updatedAt: '2024-02-05',
      },
    ],
    hasChildSubsidiaries: false,
    childSubsidiaryCount: 0,
    status: 'pending',
    createdAt: '2022-09-01',
    updatedAt: '2024-02-05',
  },
];

// Helper function to get subsidiary by ID
export function getSubsidiaryById(id: string): SubsidiaryCompany | undefined {
  return SUBSIDIARIES.find(sub => sub.id === id);
}

// Helper function to get all locations across all subsidiaries
export function getAllLocations(): { subsidiary: SubsidiaryCompany; location: Location }[] {
  const result: { subsidiary: SubsidiaryCompany; location: Location }[] = [];
  SUBSIDIARIES.forEach(sub => {
    sub.locations.forEach(loc => {
      result.push({ subsidiary: sub, location: loc });
    });
  });
  return result;
}

// Helper function to get unique countries
export function getUniqueCountries(): string[] {
  return [...new Set(SUBSIDIARIES.map(sub => sub.country))].sort();
}

// Helper function to get unique cities
export function getUniqueCities(): string[] {
  return [...new Set(SUBSIDIARIES.map(sub => sub.city))].sort();
}
