import type { ReportData } from './report-data';
import {
  NOT_CALCULATED,
  esc,
  pdfLedgerHeadRow,
  pdfLedgerRow,
  pdfNumber,
  pdfWithdrawnHeadRow,
  pdfWithdrawnRow,
  pdfWithdrawnTotalRow,
} from './report-columns';

/**
 * Branded, self-contained HTML for the audit-ready PDF (FR §5.1). Pure function
 * of the assembled data — no I/O — so it is unit-testable without Puppeteer.
 * Puppeteer renders this via `page.setContent` (no web route, no auth replay).
 */

const STATUS_LABEL: Record<string, { text: string; color: string }> = {
  approved: { text: 'Approved', color: '#059669' },
  draft: { text: 'Draft — records pending review', color: '#2563eb' },
  contains_incomplete_data: { text: 'Contains incomplete data', color: '#d97706' },
};

export function buildReportHtml(data: ReportData): string {
  const s = STATUS_LABEL[data.status];
  const isDetail = data.template === 'ghg_protocol_detail';

  const categoryRows = data.summary.byCategory
    .map(
      (c) => `<tr><td>${esc(c.category)}</td><td>Scope ${c.scope}</td>
        <td class="num">${pdfNumber.format(c.tCo2e)}</td><td class="num">${pdfNumber.format(c.percentOfTotal)}%</td>
        <td class="num">${c.recordCount}</td></tr>`,
    )
    .join('');

  const subsidiaryRows = data.summary.bySubsidiary
    .map(
      (r) => `<tr><td>${esc(r.subsidiaryName)}</td>
        <td class="num">${pdfNumber.format(r.tCo2e)}</td><td class="num">${pdfNumber.format(r.percentOfTotal)}%</td>
        <td class="num">${r.recordCount}</td></tr>`,
    )
    .join('');

  const ledgerRows = isDetail ? data.records.map(pdfLedgerRow).join('') : '';

  const factorRows = data.factors
    .map(
      (f) => `<tr><td>${esc(f.category)}</td><td>${esc(f.geographyCode)}</td>
      <td class="num">${f.factorValue} ${esc(f.factorUnit)}</td><td>${esc(f.methodology)}</td>
      <td>${esc(f.source)}</td><td>${esc(f.version)}</td></tr>${
        f.conversionBasis
          ? `<tr><td colspan="6" class="note">Unit conversion applied before this factor: ${esc(f.conversionBasis)}</td></tr>`
          : ''
      }`,
    )
    .join('');

  // Every cell here is user-authored — a site name and a free-text reason of up
  // to 2,000 characters — so all of it goes through `esc`.
  const withdrawnRows = data.withdrawn.map(pdfWithdrawnRow).join('');

  const evidenceRows = data.evidenceSummary
    .map(
      (e) => `<tr><td>${esc(e.subsidiaryName)}</td><td>${esc(e.category)} · ${esc(e.periodValue)}</td>
      <td class="num">${e.fileCount}</td><td>${esc(e.fileNames.join(', '))}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
  * { box-sizing: border-box; margin: 0; }
  body { font-family: 'Inter', -apple-system, 'Helvetica Neue', Arial, sans-serif; color: #1d1d1f; padding: 40px 48px; font-size: 12px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #059669; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 22px; color: #059669; } h2 { font-size: 14px; margin: 24px 0 8px; color: #1d1d1f; }
  .meta { text-align: right; color: #6e6e73; font-size: 11px; line-height: 1.6; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; color: #fff; font-weight: 600; font-size: 11px; background: ${s.color}; }
  .tiles { display: flex; gap: 12px; margin: 16px 0; }
  .tile { flex: 1; border: 1px solid #e5e5ea; border-radius: 10px; padding: 12px 16px; }
  .tile .v { font-size: 20px; font-weight: 700; } .tile .l { color: #6e6e73; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; color: #6e6e73; border-bottom: 1.5px solid #d2d2d7; padding: 6px 8px; }
  td { padding: 6px 8px; border-bottom: 1px solid #f0f0f2; } .num { text-align: right; font-variant-numeric: tabular-nums; }
  .warn { background: #fffbeb; border: 1px solid #fde68a; color: #92400e; border-radius: 8px; padding: 10px 14px; margin: 12px 0; }
  .note { color: #6e6e73; font-size: 10px; margin-top: 4px; }
  footer { margin-top: 28px; border-top: 1px solid #e5e5ea; padding-top: 10px; color: #6e6e73; font-size: 10px; }
  </style></head><body>
  <header>
    <div>
      <h1>${esc(data.organisationName)}</h1>
      <div>${esc(data.templateName)} · Reporting year ${data.year}${data.subsidiaryName ? ` · ${esc(data.subsidiaryName)}` : ''}</div>
    </div>
    <div class="meta">
      <span class="badge">${s.text}</span><br/>
      Generated ${esc(data.generatedAt)}<br/>Generated by ${esc(data.generatedBy)}
    </div>
  </header>

  ${
    data.incompleteRatio > 0.15
      ? `<div class="warn"><strong>Data warning:</strong> ${pdfNumber.format(data.incompleteRatio * 100)}% of this period's records are draft/rejected — not suitable for final reporting.</div>`
      : ''
  }

  <div class="tiles">
    <div class="tile"><div class="l">Scope 1</div><div class="v">${pdfNumber.format(data.summary.totals.scope1)} tCO₂e</div></div>
    <div class="tile"><div class="l">Scope 2</div><div class="v">${pdfNumber.format(data.summary.totals.scope2)} tCO₂e</div></div>
    <div class="tile"><div class="l">Total</div><div class="v">${pdfNumber.format(data.summary.totals.total)} tCO₂e</div></div>
    <div class="tile"><div class="l">Committed records</div><div class="v">${data.summary.recordCount}</div></div>
  </div>
  ${
    data.summary.uncalculatedRecordCount > 0
      ? `<p class="note"><strong>${data.summary.uncalculatedRecordCount}</strong> of these ${data.summary.recordCount} records carry no emissions figure, because no emission factor is available for their category. They are listed in the detail ledger as &ldquo;${NOT_CALCULATED}&rdquo; and contribute nothing to the totals above.</p>`
      : ''
  }
  ${
    data.withdrawn.length > 0
      ? `<div class="warn"><strong>Restatement:</strong> ${data.withdrawnTotals.count} ${
          data.withdrawnTotals.count === 1
            ? 'record was withdrawn from this reporting year after approval, removing'
            : 'records were withdrawn from this reporting year after approval, removing'
        } <strong>${pdfNumber.format(data.withdrawnTotals.tCo2e)} tCO₂e</strong> from the inventory.${
          data.withdrawnTotals.uncalculatedCount > 0
            ? ` ${data.withdrawnTotals.uncalculatedCount} of them carry no emissions figure, so withdrawing ${
                data.withdrawnTotals.uncalculatedCount === 1 ? 'it' : 'them'
              } removed no tonnage.`
            : ''
        } ${
          data.withdrawnTotals.count === 1 ? 'It counts' : 'They count'
        } towards no figure in this report, and ${
          data.withdrawnTotals.count === 1 ? 'it is' : 'they are'
        } listed under &ldquo;Withdrawn from this inventory&rdquo; below with the reason recorded at the time.</div>`
      : ''
  }
  <p class="note">Scope 3 is out of scope for Phase 1. Figures are computed from committed activity records using prototype demo emission factors — not authoritative DEFRA/AIB values.</p>

  <h2>Emissions by category</h2>
  <table><thead><tr><th>Category</th><th>Scope</th><th class="num">tCO₂e</th><th class="num">% of total</th><th class="num">Records</th></tr></thead>
  <tbody>${categoryRows || '<tr><td colspan="5">No committed data for this selection.</td></tr>'}</tbody></table>

  <h2>Subsidiary performance</h2>
  <table><thead><tr><th>Subsidiary</th><th class="num">tCO₂e</th><th class="num">% of total</th><th class="num">Records</th></tr></thead>
  <tbody>${subsidiaryRows || '<tr><td colspan="4">No committed data for this selection.</td></tr>'}</tbody></table>

  ${
    isDetail
      ? `<h2>Activity records ledger</h2>
  <table><thead>${pdfLedgerHeadRow()}</thead>
  <tbody>${ledgerRows}</tbody></table>`
      : ''
  }

  ${
    // Deliberately NOT gated on `isDetail`, unlike the ledger above it: a
    // restatement is a disclosure, not a detail appendix, and the template a
    // board actually reads is the Executive Summary. Hiding it there would
    // recreate the omission this section exists to end.
    data.withdrawn.length > 0
      ? `<h2>Withdrawn from this inventory</h2>
  <p class="note">These figures were approved and then withdrawn. They stop counting towards totals, reports and invoice coverage from the moment of withdrawal, so nothing above includes them; each entry stays on record with the reason given, and the withdrawal itself is in the audit log. A withdrawal is not a deletion — the period it covered reopens so a corrected figure can be entered in its place.</p>
  <table><thead>${pdfWithdrawnHeadRow()}</thead>
  <tbody>${withdrawnRows}${pdfWithdrawnTotalRow(data.withdrawnTotals)}</tbody></table>`
      : ''
  }

  ${
    data.includeMethodologyNotes
      ? `<h2>Methodology & emission factors</h2>
  <p class="note">Every calculation stores an immutable snapshot of the factor it used (value, source, version) and of any unit conversion applied before it, so each figure in the ledger can be recomputed from this report; historic results never change. Boundary: operational control. Aligned with ISO 14064-1 / GHG Protocol.</p>
  <table><thead><tr><th>Category</th><th>Geography</th><th class="num">Factor</th><th>Methodology</th><th>Source</th><th>Version</th></tr></thead>
  <tbody>${factorRows}</tbody></table>`
      : ''
  }

  ${
    data.includeEvidenceSummary && evidenceRows
      ? `<h2>Evidence summary</h2>
  <p class="note">File names and counts of the supporting evidence attached to committed records (files live in secure storage; links are intentionally not embedded because they expire).</p>
  <table><thead><tr><th>Subsidiary</th><th>Record</th><th class="num">Files</th><th>File names</th></tr></thead>
  <tbody>${evidenceRows}</tbody></table>`
      : ''
  }

  <footer>TonyAI — Enterprise Carbon Accounting & ESG Platform · ${esc(data.templateName)} · ${data.year} · Statuses included: ${data.summary.statusesIncluded.join(', ')}</footer>
  </body></html>`;
}
