import type { ReportData } from './reports.service';

/**
 * Branded, self-contained HTML for the audit-ready PDF (FR §5.1). Pure function
 * of the assembled data — no I/O — so it is unit-testable without Puppeteer.
 * Puppeteer renders this via `page.setContent` (no web route, no auth replay).
 */

const fmt = new Intl.NumberFormat('en-GB', { maximumFractionDigits: 1 });

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const STATUS_LABEL: Record<string, { text: string; color: string }> = {
  approved: { text: 'Approved', color: '#059669' },
  draft: { text: 'Draft — records pending review', color: '#2563eb' },
  contains_incomplete_data: { text: 'Contains incomplete data', color: '#d97706' },
};

export function buildReportHtml(data: ReportData): string {
  const s = STATUS_LABEL[data.status];
  const isDetail = data.template === 'ghg_protocol_detail';

  const categoryRows = data.summary.byCategory
    .map(
      (c) => `<tr><td>${esc(c.category)}</td><td>Scope ${c.scope}</td>
        <td class="num">${fmt.format(c.tCo2e)}</td><td class="num">${fmt.format(c.percentOfTotal)}%</td>
        <td class="num">${c.recordCount}</td></tr>`,
    )
    .join('');

  const subsidiaryRows = data.summary.bySubsidiary
    .map(
      (r) => `<tr><td>${esc(r.subsidiaryName)}</td>
        <td class="num">${fmt.format(r.tCo2e)}</td><td class="num">${fmt.format(r.percentOfTotal)}%</td>
        <td class="num">${r.recordCount}</td></tr>`,
    )
    .join('');

  const ledgerRows = isDetail
    ? data.records
        .map(
          (r) => `<tr><td>${esc(r.subsidiaryName)}</td><td>${esc(r.category)}</td>
          <td>${esc(r.periodValue)}</td><td class="num">${fmt.format(r.activityValue)} ${esc(r.activityUnit)}</td>
          <td class="num">${fmt.format(r.tCo2e)}</td><td>${esc(r.status)}</td>
          <td class="num">${r.evidenceCount}</td></tr>`,
        )
        .join('')
    : '';

  const factorRows = data.factors
    .map(
      (f) => `<tr><td>${esc(f.category)}</td><td>${esc(f.geographyCode)}</td>
      <td class="num">${f.factorValue} ${esc(f.factorUnit)}</td><td>${esc(f.methodology)}</td>
      <td>${esc(f.source)}</td><td>${esc(f.version)}</td></tr>`,
    )
    .join('');

  const evidenceRows = data.evidenceSummary
    .map(
      (e) => `<tr><td>${esc(e.subsidiaryName)}</td><td>${esc(e.category)} · ${esc(e.periodValue)}</td>
      <td class="num">${e.fileCount}</td><td>${esc(e.fileNames.join(', '))}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
  * { box-sizing: border-box; margin: 0; }
  body { font-family: 'Inter', -apple-system, 'Helvetica Neue', Arial, sans-serif; color: #1d1d1f; padding: 40px 48px; font-size: 12px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #059669; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 22px; color: #059669; } h2 { font-size: 14px; margin: 24px 0 8px; color: #1d1d1f; }
  .meta { text-align: right; color: #6e6e73; font-size: 11px; line-height: 1.6; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; color: #fff; font-weight: 600; font-size: 11px; background: ${s.color}; }
  .tiles { display: flex; gap: 12px; margin: 16px 0; }
  .tile { flex: 1; border: 1px solid #e5e5ea; border-radius: 10px; padding: 12px 16px; }
  .tile .v { font-size: 20px; font-weight: 700; } .tile .l { color: #6e6e73; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; color: #6e6e73; border-bottom: 1.5px solid #d2d2d7; padding: 6px 8px; }
  td { padding: 6px 8px; border-bottom: 1px solid #f0f0f2; } .num { text-align: right; font-variant-numeric: tabular-nums; }
  .warn { background: #fffbeb; border: 1px solid #fde68a; color: #92400e; border-radius: 8px; padding: 10px 14px; margin: 12px 0; }
  .note { color: #6e6e73; font-size: 10px; margin-top: 4px; }
  footer { margin-top: 28px; border-top: 1px solid #e5e5ea; padding-top: 10px; color: #6e6e73; font-size: 10px; }
  </style></head><body>
  <header>
    <div>
      <h1>${esc(data.organisationName)}</h1>
      <div>${esc(data.templateName)} · Reporting year ${data.year}${data.subsidiaryName ? ` · ${esc(data.subsidiaryName)}` : ''}</div>
    </div>
    <div class="meta">
      <span class="badge">${s.text}</span><br/>
      Generated ${esc(data.generatedAt)}<br/>Generated by ${esc(data.generatedBy)}
    </div>
  </header>

  ${
    data.incompleteRatio > 0.15
      ? `<div class="warn"><strong>Data warning:</strong> ${fmt.format(data.incompleteRatio * 100)}% of this period's records are draft/rejected — not suitable for final reporting.</div>`
      : ''
  }

  <div class="tiles">
    <div class="tile"><div class="l">Scope 1</div><div class="v">${fmt.format(data.summary.totals.scope1)} tCO₂e</div></div>
    <div class="tile"><div class="l">Scope 2</div><div class="v">${fmt.format(data.summary.totals.scope2)} tCO₂e</div></div>
    <div class="tile"><div class="l">Total</div><div class="v">${fmt.format(data.summary.totals.total)} tCO₂e</div></div>
    <div class="tile"><div class="l">Committed records</div><div class="v">${data.summary.recordCount}</div></div>
  </div>
  <p class="note">Scope 3 is out of scope for Phase 1. Figures are computed from committed activity records using prototype demo emission factors — not authoritative DEFRA/AIB values.</p>

  <h2>Emissions by category</h2>
  <table><thead><tr><th>Category</th><th>Scope</th><th class="num">tCO₂e</th><th class="num">% of total</th><th class="num">Records</th></tr></thead>
  <tbody>${categoryRows || '<tr><td colspan="5">No committed data for this selection.</td></tr>'}</tbody></table>

  <h2>Subsidiary performance</h2>
  <table><thead><tr><th>Subsidiary</th><th class="num">tCO₂e</th><th class="num">% of total</th><th class="num">Records</th></tr></thead>
  <tbody>${subsidiaryRows || '<tr><td colspan="4">No committed data for this selection.</td></tr>'}</tbody></table>

  ${
    isDetail
      ? `<h2>Activity records ledger</h2>
  <table><thead><tr><th>Subsidiary</th><th>Category</th><th>Period</th><th class="num">Activity</th><th class="num">tCO₂e</th><th>Status</th><th class="num">Evidence</th></tr></thead>
  <tbody>${ledgerRows}</tbody></table>`
      : ''
  }

  ${
    data.includeMethodologyNotes
      ? `<h2>Methodology & emission factors</h2>
  <p class="note">Every calculation stores an immutable snapshot of the factor it used (value, source, version); historic results never change. Boundary: operational control. Aligned with ISO 14064-1 / GHG Protocol.</p>
  <table><thead><tr><th>Category</th><th>Geography</th><th class="num">Factor</th><th>Methodology</th><th>Source</th><th>Version</th></tr></thead>
  <tbody>${factorRows}</tbody></table>`
      : ''
  }

  ${
    data.includeEvidenceSummary && evidenceRows
      ? `<h2>Evidence summary</h2>
  <p class="note">File names and counts of the supporting evidence attached to committed records (files live in secure storage; links are intentionally not embedded because they expire).</p>
  <table><thead><tr><th>Subsidiary</th><th>Record</th><th class="num">Files</th><th>File names</th></tr></thead>
  <tbody>${evidenceRows}</tbody></table>`
      : ''
  }

  <footer>TonyAI — Enterprise Carbon Accounting & ESG Platform · ${esc(data.templateName)} · ${data.year} · Statuses included: ${data.summary.statusesIncluded.join(', ')}</footer>
  </body></html>`;
}
